// <auto-generated />
using BookshopMVC.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookshopMVC.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240702205517_SeedProductTable")]
    partial class SeedProductTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BookshopMVC.Models.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 1,
                            Name = "Action"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 2,
                            Name = "SciFi"
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 3,
                            Name = "History"
                        });
                });

            modelBuilder.Entity("BookshopMVC.Models.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Robert C. Martin",
                            Description = "A Handbook of Agile Software Craftsmanship",
                            Price = 35.990000000000002,
                            Title = "Clean Code"
                        },
                        new
                        {
                            Id = 2,
                            Author = "Michael E. Gerber",
                            Description = "Why Most Small Businesses Don't Work and What to Do About It",
                            Price = 29.989999999999998,
                            Title = "The E-Myth Revisited"
                        },
                        new
                        {
                            Id = 3,
                            Author = "Mark Hyman",
                            Description = "Fix Your Broken Brain by Healing Your Body First",
                            Price = 24.989999999999998,
                            Title = "The UltraMind Solution"
                        },
                        new
                        {
                            Id = 4,
                            Author = "Sun Tzu",
                            Description = "An Ancient Chinese Classic on Military Strategy",
                            Price = 19.989999999999998,
                            Title = "The Art of War"
                        },
                        new
                        {
                            Id = 5,
                            Author = "Napoleon Hill",
                            Description = "The Landmark Bestseller Now Revised and Updated for the 21st Century",
                            Price = 14.99,
                            Title = "Think and Grow Rich"
                        },
                        new
                        {
                            Id = 6,
                            Author = "Dale Carnegie",
                            Description = "The Only Book You Need to Lead You to Success",
                            Price = 22.989999999999998,
                            Title = "How to Win Friends and Influence People"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
